# Generated by Django 3.0.8 on 2020-07-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_person_shirts'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('study', models.CharField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth')], max_length=1)),
            ],
        ),
    ]
