# Generated by Django 3.0.8 on 2020-07-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_school_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='school_student',
            name='study',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth')]),
        ),
    ]
