# Generated by Django 3.0.8 on 2020-07-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20200726_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['age']},
        ),
    ]
