# Generated by Django 3.0.8 on 2020-07-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20200726_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['-id']},
        ),
    ]
