# Generated by Django 3.0.8 on 2020-07-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('Reg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Branch', models.CharField(choices=[('ECE', 'Electronics'), ('CSE', 'Computers'), ('MECH', 'mechanics'), ('EEE', 'Electrics')], max_length=4)),
            ],
            options={
                'ordering': ['Reg_id'],
            },
        ),
    ]
