# Generated by Django 3.0.8 on 2020-07-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('profile', models.ImageField(null=True, upload_to='')),
                ('date_of_birth', models.DateField(null=True)),
            ],
        ),
    ]
