# Generated by Django 3.0.8 on 2020-07-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_new_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_model',
            name='description',
            field=models.TextField(default='sathya'),
            preserve_default=False,
        ),
    ]
